version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: django-app
    command: >
      bash -c "
      python ssm_loader.py &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      AWS_DEFAULT_REGION: ap-south-1
      AWS_SSM_PATH_PREFIX: /python-demo/

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: machine_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
